### PR TITLE
🚀v0.3.308 (dev) --> master

### PR DESCRIPTION
**Pull request by dudeisbrendan03**
Let's merge and deploy!!! 🚀
___________________________________
A few tasks before merging:

- ~~Instance token promotion should return true errors instead of vague~~
- ~~Operator tokens should be forced to 30 minutes~~
- ~~Operator tokens shouldn't be renewable~~
___________________________________

Versioning:

v[major].[minor].[commit no.]
v0.3.308

### CODE REVIEW

**Comment by dudeisbrendan03** [comment]
@Superigi Come review child, need to check for any extra bugs then squish them before making this release

**Comment by dudeisbrendan03** [comment]
@Superigi after you've tested a feature please update the tags on Azure DevOps from `Needs Testing` to `Passed Testing`

**Comment by dudeisbrendan03** [comment]
https://github.com/dudeisbrendan03/RESTful-api/releases/tag/0.3.305

Beta release flagged

**Comment by dudeisbrendan03** [comment]
@Superigi this is now overdue, not a single test has been performed.

**Comment by dudeisbrendan03** [comment]
@Superigi this has been open for 12 days now

**Comment by dudeisbrendan03** [comment]
Don't just flag everything as tested when you haven't tested it.

**Comment by dudeisbrendan03** [comment]
Igor has been temporarily removed so I can complete this.

**Comment by dudeisbrendan03** [comment]
hashVerify in etclib requires fixing, then we're good for a merge.

**Comment by Superigi** [comment]
> hashVerify in etclib requires fixing, then we're good for a merge.

been moved to 0.4x

**Comment by dudeisbrendan03** [comment]
> > hashVerify in etclib requires fixing, then we're good for a merge.
> 
> been moved to 0.4x

I didn't do that or anything so I don't know or anything

**Comment by dudeisbrendan03** [comment]
Also, welcome to the project you're a month late!

**Comment by Superigi** [comment]
> Also, welcome to the project you're a month late!

yeah just realised soz

**Comment by dudeisbrendan03** [comment]
Already did the testing, feel free to review +approve.

**Review by Superigi — APPROVED** [review]
I'm only 2 months late

**Pull request merged**
